site_name: CPSC 129

site_description: Yukon University > CPSC 129 Object-oriented Programming 2
site_author: Tim Topper and Kate Chatfield-Reed
site_url: https://ttopper.github.io/CPSC129
repo_url: https://github.com/ttopper/CPSC129
edit_uri: edit/main/docs/

copyright:
  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported License</a>.

watch:
- custom_theme
# It didn't seem to watch this automatically ?! so I added it here explicitly.

theme:
  name: mkdocs
  custom_dir: custom_theme/
  locale: en
  highlightjs: true
  hljs_languages:
    - python
#    - django

extra_css: 
 - extra.css

# extra_javascript:
#  - extra.js

# Python-Markdown extensions, see https://python-markdown.github.io/extensions/
markdown_extensions:
  # - smarty # Enter Unicode characters instead!
  - abbr
  - attr_list
  - def_list
  - fenced_code
  - footnotes
  - tables
  - admonition
#  - codehilite # Use highlightjs within mkdocs instead
  - sane_lists

plugins:
  - search

nav:
  - Notes: 
    - index.md
    - 01.1 Course Information:
      - Contents: 01.1_Course_Information/00_index.md
      - Course Schedule: 01.1_Course_Information/01_Course_schedule.md
      - Marking Scheme: 01.1_Course_Information/02_Marking_scheme.md
    - 01.2 Conway's Game of Life 1:
      - Contents: 01.2_CGoL_1_Introduction/00_index.md
      - Introduction: 01.2_CGoL_1_Introduction/01_Introduction.md
      - Algorithm Overview: 01.2_CGoL_1_Introduction/02_Algorithm_overview.md
      - Create and Initialize the Universe: 01.2_CGoL_1_Introduction/03_Create_and_initialize_U.md
      - Display the Universe: 01.2_CGoL_1_Introduction/04_Display.md
      - Age the Universe: 01.2_CGoL_1_Introduction/05_Age.md
    - Assignment 1: Assignments/Assignment_01.md
    - 02.1 Searching:
      - Contents: 02.1_Searching/00_index.md
      - Introduction: 02.1_Searching/01_Introduction.md
      - Linear Search, Unordered list: 02.1_Searching/02_Linear_Search_Unordered_List.md
      - Linear Search, Ordered List: 02.1_Searching/03_Linear_Search_Ordered_List.md
      - Binary Search: 02.1_Searching/04_Binary_Search.md
      - Interpolative Search: 02.1_Searching/05_Interpolative_Search.md
    - 02.2 Algorithm Analysis: 
      - Contents: 02.2_Algorithm_Analysis/00_index.md
      - 02.2_Algorithm_Analysis/01_Introduction.md
      - 02.2_Algorithm_Analysis/02_Big_O_notation.md
      - 02.2_Algorithm_Analysis/03_Linear_search.md
      - 02.2_Algorithm_Analysis/04_Binary_search.md
      - 02.2_Algorithm_Analysis/05_O_log_n_vs_O_n.md
      - 02.2_Algorithm_Analysis/06_Algorithm_orders.md
    - 02.3 PyGame 1 Drawing:
      - Contents: 02.3_PyGame_1_Drawing/00_index.md
      - 02.3_PyGame_1_Drawing/01_Introduction.md
      - 02.3_PyGame_1_Drawing/02_pygame_test_0.md
      - 02.3_PyGame_1_Drawing/03_pygame_test_1.md
      - 02.3_PyGame_1_Drawing/04_pygame_test_2.md
      - 02.3_PyGame_1_Drawing/05_pygame_test_3.md
      - 02.3_PyGame_1_Drawing/06_pygame_test_4.md
      - 02.3_PyGame_1_Drawing/07_pygame_test_5.md
    - Assignment 2: Assignments/Assignment_02.md
    - 03.1 Recursion:
      - Contents: 03.1_Recursion/00_index.md
      - 03.1_Recursion/01_Recursion_by_example.md
      - 03.1_Recursion/02_Recursion_through_a_list.md
      - 03.1_Recursion/03_Calculating_factorials.md
      - 03.1_Recursion/04_Recursive_binary_search.md
      - 03.1_Recursion/05_Recursive_data_structures.md
      - 03.1_Recursion/06_recursion.md
      - 03.1_Recursion/07_Notes.md
    - 03.2 File Processing:
      - Contents: 03.2_File_Processing/00_index.md
      - 03.2_File_Processing/01_Persistence.md
      - 03.2_File_Processing/02_Text_vs_binary_files.md
      - 03.2_File_Processing/03_Reading_from_text_files.md
      - 03.2_File_Processing/04_Example_searching_log_files.md
      - 03.2_File_Processing/05_Files_are_sequential.md
      - 03.2_File_Processing/06_Is_there_more.md
      - 03.2_File_Processing/07_Writing_to_text_files.md
      - 03.2_File_Processing/08_Appending_to_files.md
      - 03.2_File_Processing/09_Reading_numeric_data.md
    - 03.3 CGoL 2 Persistence:
      - Contents: 03.3_CGoL_2_Persistence/00_index.md
      - 03.3_CGoL_2_Persistence/01_Introduction.md
      - 03.3_CGoL_2_Persistence/02_Goal.md
      - 03.3_CGoL_2_Persistence/03_Option_1_Screenshot.md
      - 03.3_CGoL_2_Persistence/04_Option_2_Python_list.md
      - 03.3_CGoL_2_Persistence/05_Option_3_Coordinate_list.md
      - 03.3_CGoL_2_Persistence/06_Option_4_Bits.md
      - 03.3_CGoL_2_Persistence/07_Pickling.md
    - 04.1 CRUD:
      - Contents: 04.1_CRUD/00_index.md
      - 04.1_CRUD/01_Persistence.md
      - 04.1_CRUD/02_Pickling.md
      - 04.1_CRUD/03_Shelves.md
      - 04.1_CRUD/04_Shelve_gotcha.md
      - 04.1_CRUD/05_Controller.md
      - 04.1_CRUD/06_The_main_event_loop.md
    - Assignment 3: Assignments/Assignment_03.md
    - 04.2 MVC 1:
      - Contents: 04.2_MVC_1/00_index.md
      - 04.2_MVC_1/01_Introduction.md
      - 04.2_MVC_1/02_Step_1_Identify_model.md
      - 04.2_MVC_1/03_Step_2_Start_the_model.md
      - 04.2_MVC_1/04_Step_3_The_quote_class.md
      - 04.2_MVC_1/05_UIDs.md
      - 04.2_MVC_1/06_Step_4_Model_revisited_for_testing.md
      - 04.2_MVC_1/07_Step_5_Controller_revisited.md
    - 04.3 PyGame 2 Animation:
      - Contents: 04.3_PyGame_2_Animation/00_index.md
      - 04.3_PyGame_2_Animation/01_Introduction.md
      - 04.3_PyGame_2_Animation/02_pygame_test_6.md
      - 04.3_PyGame_2_Animation/03_pygame_test_7.md
      - 04.3_PyGame_2_Animation/04_pygame_test_8.md
      - 04.3_PyGame_2_Animation/05_pygame_test_9.md
      - 04.3_PyGame_2_Animation/06_pygame_test_10.md
    - Assignment 4: Assignments/Assignment_04.md
    - 05.1 Sorting 1:
      - Contents: 05.1_Sorting_1/00_index.md
      - 05.1_Sorting_1/01_Sorting_out_sorting.md
      - 05.1_Sorting_1/02_Straight_insertion_sort.md
      - 05.1_Sorting_1/03_Straight_selection_sort.md
      - 05.1_Sorting_1/04_Straight_exchange_sort.md
      - 05.1_Sorting_1/05_Shell_sort.md
    - 05.2 CGoL 3 Speed:
      - Contents: 05.2_CGoL_3_Speed/00_index.md
      - 05.2_CGoL_3_Speed/01_Where_to_begin.md
      - 05.2_CGoL_3_Speed/02_Measure_dont_guess.md
      - 05.2_CGoL_3_Speed/03_Reworking_aging.md
      - 05.2_CGoL_3_Speed/04_The_new_aging_scheme.md
      - 05.2_CGoL_3_Speed/05_Measure_again.md
    - Assignment 5: Assignments/Assignment_05.md
    - 06.1 MVC 2:
      - Contents: 06.1_MVC_2/00_index.md
      - 06.1_MVC_2/01_The_issue.md
      - 06.1_MVC_2/02_The_payoff.md
      - 06.1_MVC_2/03_Separating_controller_and_quote.md
      - 06.1_MVC_2/04_Quote_factory.md
      - 06.1_MVC_2/05_Adding_more_object_types.md
      - 06.1_MVC_2/06_Your_turn.md
    - 06.2 Mazes 1:
      - Contents: 06.2_Mazes_1/00_index.md
      - 06.2_Mazes_1/01_The_problem.md
      - 06.2_Mazes_1/02_Approaches.md
      - 06.2_Mazes_1/03_Step_1_From_english_to_pseudcode.md
      - 06.2_Mazes_1/04_Step_2_Testing_our_pseudocode.md
      - 06.2_Mazes_1/05_Step_3_Revise_pseudocode.md
      - 06.2_Mazes_1/06_Step_4_OOP.md
      - 06.2_Mazes_1/07_Step_5_Initializing_maze.md
      - 06.2_Mazes_1/08_Step_6_Debugging_output.md
      - 06.2_Mazes_1/09_Step_7_Sharing_walls.md
      - 06.2_Mazes_1/10_Step_8_Put_the_pieces_together.md
    - Assignment 6: Assignments/Assignment_06.md
    - 07.1 Sorting 2:
      - Contents: 07.1_Sorting_2/00_index.md
      - 07.1_Sorting_2/01_Introduction.md
      - 07.1_Sorting_2/02_Quicksort_1.md
      - 07.1_Sorting_2/03_Quicksort_2.md
      - 07.1_Sorting_2/04_Tree_in_a_list.md
      - 07.1_Sorting_2/05_Heapsort.md
      - 07.1_Sorting_2/Heapsort_old.md
    - 07.2 CGoL 4 GUI:
      - Contents: 07.2_CGoL_4_GUI/00_index.md
      - 07.2_CGoL_4_GUI/01_The_goal.md
      - 07.2_CGoL_4_GUI/02_Step_1_Make_a_plan.md
      - 07.2_CGoL_4_GUI/03_Step_2_Review_existing_code.md
      - 07.2_CGoL_4_GUI/04_Step_3_Test_existing_code.md
      - 07.2_CGoL_4_GUI/05_Step_4_Make_room_for_the_menu.md
      - 07.2_CGoL_4_GUI/06_Step_5_Refactoring_interlude.md
      - 07.2_CGoL_4_GUI/07_Step_6_Display_menu_icons.md
      - 07.2_CGoL_4_GUI/08_Step_7_Map_clicks_to_actions.md
      - 07.2_CGoL_4_GUI/09_Step_8_Merge_ui_and_simulation.md
    - Assignment 7: Assignments/Assignment_07.md
    - 08.1 CGI Programming:
      - Contents: 08.1_CGI/00_index.md
      - 08.1_CGI/01_Introduction.md
      - 08.1_CGI/02_Software_distribution.md
      - 08.1_CGI/03_Web_computing.md
      - 08.1_CGI/04_Introduction_to_CGI.md
      - 08.1_CGI/05_Your_first_web_server.md
      - 08.1_CGI/06_Testing_static_serving.md
      - 08.1_CGI/07_Testing_CGI_serving.md
      - 08.1_CGI/08_Toward_a_real_CGI_program.md
      - 08.1_CGI/09_The_input_form.md
      - 08.1_CGI/10_The_processing_script.md
      - 08.1_CGI/11_Unifying_input_form_and_processing_script.md
      - 08.1_CGI/12_Fancier_input.md
      - 08.1_CGI/14_Fancier_output.md
      - 08.1_CGI/Mxx_Assignment.md
      - 08.1_CGI/Stupid.md
      - 08.1_CGI/mi2km_input_v3.md
      - 08.1_CGI/mi2km_output_v3.md
      - 08.1_CGI/pWeatherServer-input.md
      - 08.1_CGI/pWeatherServer-output.md
    - 08.2 Mazes 2:
      - Contents: 08.2_Mazes_2/00_index.md
      - 08.2_Mazes_2/01_Interactive_Maze.md
    - Assignment 8: Assignments/Assignment_08.md
    - 09.1 Median Finding:
      - Contents: 09.1_Median/00_index.md
      - 09.1_Median/01_Introduction.md
      - 09.1_Median/02_median_by_partn_0.md
      - 09.1_Median/03_median_by_partn_1.md
      - 09.1_Median/04_median_by_partn_2.md
      - 09.1_Median/05_median_by_partn_3.md
      - 09.1_Median/06_median_by_bounding_0.md
      - 09.1_Median/07_median_by_bounding_1.md
      - 09.1_Median/08_median_by_bounding_2.md
      - 09.1_Median/09_median_by_bounding_3.md
    - 09.2 Data Processing:
      - Contents: 09.2_Data_Processing/00_index.md
      - 09.2_Data_Processing/01_Introduction.md
      - 09.2_Data_Processing/02_Spelling_bee_The_problem.md
      - 09.2_Data_Processing/03_Spelling_bee_Data_processing_view.md
      - 09.2_Data_Processing/04_Spelling_bee_Potential_problems.md
      - 09.2_Data_Processing/05_Python_exceptions.md
      - 09.2_Data_Processing/06_EasyGUI.md
    - Assignment 9: Assignments/Assignment_09.md
    - 10.1 HTTP and REST:
      - Contents: 10.1_HTTP_REST/00_index.md
      - 10.1_HTTP_REST/01_Introduction.md
      - 10.1_HTTP_REST/02_The_problem_with_CGI.md
      - 10.1_HTTP_REST/03_The_world_wide_web.md
      - 10.1_HTTP_REST/04_The_inner_nature_of_HTTP.md
      - 10.1_HTTP_REST/05_HTTP_on_the_wire.md
      - 10.1_HTTP_REST/06_Browsing_without_a_browser.md
      - 10.1_HTTP_REST/07_CRUD_vs_HTTP.md
      - 10.1_HTTP_REST/08_A_minimal_HTTP_server_in_python.md
      - 10.1_HTTP_REST/09_Demo_Testing_object_server.md
      - 10.1_HTTP_REST/10_The_ugly_truth_about_browsers.md
      - 10.1_HTTP_REST/11_Translating_MVC_CRUD_to_HTTP.md
      - 10.1_HTTP_REST/12_Our_HTTP_request_response_cycles.md
      - 10.1_HTTP_REST/13_Interaction_storyboard.md
      - 10.1_HTTP_REST/14_Code_reuse.md
      - 10.1_HTTP_REST/15_Mapping_actions_to_HTTP_method_URL_pairs.md
      - 10.1_HTTP_REST/16_Actual_code.md
      - 10.1_HTTP_REST/17_To_object_server_1.md
      - 10.1_HTTP_REST/18_To_object_server_2.md
      - 10.1_HTTP_REST/19_To_object_server_3.md
      - 10.1_HTTP_REST/20_To_object_server_4.md
      - 10.1_HTTP_REST/21_Something_we_re_not_doing.md
      - 10.1_HTTP_REST/22_Summary.md
      - 10.1_HTTP_REST/HTML5_template.md
      - 10.1_HTTP_REST/create_a_Quote.md
      - 10.1_HTTP_REST/home.md
      - 10.1_HTTP_REST/page_Object_Creation_Menu.md
      - 10.1_HTTP_REST/page_create_form.md
      - 10.1_HTTP_REST/page_home.md
      - 10.1_HTTP_REST/page_update_form.md
      - 10.1_HTTP_REST/page_view.md
      - 10.1_HTTP_REST/test.md
      - 10.1_HTTP_REST/test_form.md
      - 10.1_HTTP_REST/update_form.md
      - 10.1_HTTP_REST/view.md
    - 10.2 Image Processing 1:
      - Contents: 10.2_IP_1/00_index.md
      - 10.2_IP_1/01_Introduction.md
      - 10.2_IP_1/02_PIL.md
      - 10.2_IP_1/03_Test_images.md
      - 10.2_IP_1/04_IPO.md
      - 10.2_IP_1/05_Point_vs_neighbourhood.md
      - 10.2_IP_1/06_Edge_detection.md
    - Assignment 10: Assignments/Assignment_10.md
    - 11.1 Pitcher Problems:
      - Contents: 11.1_Pitcher_Problems/00_index.md
      - 11.1_Pitcher_Problems/01_The_problem.md
      - 11.1_Pitcher_Problems/02_By_hand.md
      - 11.1_Pitcher_Problems/03_Notice_what_you_did.md
      - 11.1_Pitcher_Problems/04_Identify_the_problem_type.md
      - 11.1_Pitcher_Problems/05_Formalize_the_algorithm.md
      - 11.1_Pitcher_Problems/06_Pseudocode.md
      - 11.1_Pitcher_Problems/07_Refinement.md
      - 11.1_Pitcher_Problems/08_OOP.md
      - 11.1_Pitcher_Problems/09_Pseudocode_translation.md
      - 11.1_Pitcher_Problems/10_Debugging_is_goal.md
      - 11.1_Pitcher_Problems/11_Bitwise_operations.md
      - 11.1_Pitcher_Problems/12_is_goal.md
      - 11.1_Pitcher_Problems/13_Final_program.md
    - 11.2 Reporting:
      - Contents: 11.2_Reporting/00_index.md
      - 11.2_Reporting/01_The_Problem.md
    - Assignment 11: Assignments/Assignment_11.md
    - 12.1 Image Processing 2:
      - Contents: 12.1_IP_2/00_index.md
      - 12.1_IP_2/01_Introduction.md
      - 12.1_IP_2/02_Dynamic_range.md
      - 12.1_IP_2/03_Noise_filtering.md
      - 12.1_IP_2/04_Sharpening.md
    - 12.2 YG Emails:
      - Contents: 12.2_YG_Emails/00_index.md
      - 12.2_YG_Emails/01_Algorithms_and_heuristics.md
      - 12.2_YG_Emails/02_YG_Introduction.md
      - 12.2_YG_Emails/03_YG_Goal.md
      - 12.2_YG_Emails/04_YG_Complications.md
    - Assignment 12: Assignments/Assignment_12.md
    - 13.1 Exam Preparation:
      - Contents: 13.1_Exam_Preparation/00_index.md
      - 13.1_Exam_Preparation/01_Examinable_topics.md
      - 13.1_Exam_Preparation/02_Exam_study_guide.md
      - 13.1_Exam_Preparation/03_Redacted_final_exam.md
  - Assignments:
    - 1: Assignments/Assignment_01.md
    - 2: Assignments/Assignment_02.md
    - 3: Assignments/Assignment_03.md
    - 4: Assignments/Assignment_04.md
    - 5: Assignments/Assignment_05.md
    - 6: Assignments/Assignment_06.md
    - 7: Assignments/Assignment_07.md
    - 8: Assignments/Assignment_08.md
    - 9: Assignments/Assignment_09.md
    - 10: Assignments/Assignment_10.md
    - 11: Assignments/Assignment_11.md
    - 12: Assignments/Assignment_12.md
